#!/bin/sh -e
# initramfs init-bottom script for udev

PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac


# Stop udevd, we'll miss a few events while we run init, but we catch up
udevadm control --timeout=121 --exit || \
	echo "udev exit failed -- rc=$?"

# Move /dev to the real filesystem
mount -n -o move /dev ${rootmnt}/dev
